// Bundles src/worker/main.ts into a self-contained CommonJS string so the
// pool can spawn workers with `new Worker(source, { eval: true })` regardless
// of how the host application is bundled. Output: src/generated/workerSource.ts
import { buildSync } from "esbuild";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = buildSync({
  entryPoints: [join(root, "src/worker/main.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  write: false,
  legalComments: "none",
});

const code = result.outputFiles[0].text;
const banner = "// GENERATED by scripts/build-worker.mjs — do not edit.\n";
const body = `${banner}export const workerSource: string = ${JSON.stringify(code)};\n`;
const output = join(root, "src/generated/workerSource.ts");

// --check fails only on drift from a previous generation; a missing file
// (fresh clone — src/generated/ is gitignored) is bootstrapped, not an error.
const checkMode = process.argv.includes("--check");
if (checkMode && existsSync(output) && readFileSync(output, "utf8") !== body) {
  throw new Error(
    "src/generated/workerSource.ts is stale; run pnpm build:worker",
  );
}
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, body);
console.log(
  `workerSource.ts ${checkMode ? "verified" : "generated"} (${(code.length / 1024).toFixed(1)} KiB)`,
);
